"""
Account Models

Dataclasses for account plans (which products each customer should hold)
and handles (links to concrete accounts in TuringCore).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class AccountPlan:
    """
    Plan for which products each customer should hold.
    
    This is generated by the account generator based on customer segment,
    income band, and product catalog.
    """
    
    customer_external_ref: str
    product_codes: List[str]


@dataclass
class AccountHandle:
    """
    Link to concrete accounts in TuringCore.
    
    After calling OpenAccount, we store this handle to track
    the mapping from customer to their accounts.
    
    Includes customer_external_ref to enable account resolution
    mapping for transaction generation.
    """
    
    customer_external_ref: str
    customer_id: str
    account_id: str
    product_code: str
