# Weekly Risk Brain Governance Report

---

## 🟦 COVER PAGE

**Title:** Weekly Risk Brain Governance Report

**Tenant:** {{tenant_name}}  
**Reporting Period:** {{period_start}} → {{period_end}}  
**Generated:** {{generated_timestamp_utc}}  
**Version:** v1.0 (Canonical)

---

**Mandatory Footer:**

> "This document reports shadow-only AI intelligence. No AI-origin financial execution is possible by design."

---

## 📄 PAGE 1 — EXECUTIVE SUMMARY

### 1. Risk Brain Status

| Domain | Shadow Active | CI Harness | Kill-Switch Activations |
|--------|---------------|------------|-------------------------|
| Payments | {{payments_shadow}} | {{payments_ci}} | {{payments_killswitch}} |
| Fraud | {{fraud_shadow}} | {{fraud_ci}} | {{fraud_killswitch}} |
| AML | {{aml_shadow}} | {{aml_ci}} | {{aml_killswitch}} |
| Treasury | {{treasury_shadow}} | {{treasury_ci}} | {{treasury_killswitch}} |

### 2. Safety & Governance

**AI-Origin Execution Violations:** {{ai_origin_violations}}  
**Schema Violations:** {{schema_violations}}  
**Policy Origin Violations:** {{policy_origin_violations}}

**✅ Declarative Statement (MANDATORY):**

> "No AI-origin execution attempts were detected. No AI-controlled financial actions occurred during this reporting period."

### 3. Key Weekly Movements (Auto-Narrative)

**Payments optimisation trend:** {{payments_trend_summary}}

**Fraud anomalies:** {{fraud_trend_summary}}

**AML behavioural drift:** {{aml_trend_summary}}

**Treasury liquidity posture:** {{treasury_trend_summary}}

---

## 📄 PAGE 2 — PAYMENTS RL (SHADOW)

### Coverage

**% of Payments Evaluated by RL:** {{payments_coverage_pct}}%

### Directional Benefit Split

| Direction | Count |
|-----------|-------|
| RL Better | {{payments_better}} |
| RL Worse | {{payments_worse}} |
| Neutral | {{payments_neutral}} |

### Board Interpretation (Auto-Text)

> "Shadow RL suggests {{payments_coverage_pct}}% of payments could benefit from alternative routing or timing. Net optimisation signal remains {{payments_net_signal}}."

---

## 📄 PAGE 3 — FRAUD SHADOW

| Metric | Value |
|--------|-------|
| High-Risk Flags | {{fraud_high_flags}} |
| Confirmed Fraud | {{fraud_confirmed}} |
| Cleared | {{fraud_cleared}} |

### Narrative

> "Fraud activity remained {{fraud_risk_state}}. No systemic merchant, geo, or device cluster escalation detected."

---

## 📄 PAGE 4 — AML SHADOW

### Risk Band Distribution

| Risk Band | Count |
|-----------|-------|
| High | {{aml_high_flags}} |
| Medium | {{aml_medium_flags}} |

### Outcome

| Outcome | Count |
|---------|-------|
| SMRs | {{aml_smrs}} |

### Narrative

> "Behavioural AML patterns remained within baseline volatility. No cross-border structuring clusters exceeded alert threshold."

---

## 📄 PAGE 5 — TREASURY RL (SHADOW)

| Metric | Value |
|--------|-------|
| High-Risk Liquidity Windows | {{treasury_high_risk_windows}} |
| Avg Recommended Buffer Uplift | {{treasury_avg_buffer_delta_dollars}} |

### Narrative

> "No liquidity stress events predicted beyond existing governance thresholds."

---

## 📄 PAGE 6 — GOVERNANCE ATTESTATION

| Control | Status |
|---------|--------|
| AI Can Execute Financial Actions | ❌ Impossible |
| Human Policy Gate Required | ✅ Enforced |
| Kill-Switch Available | ✅ Enforced |
| Protocol Event Replay | ✅ Available |
| Regulator Annex Ready | ✅ Available |

### Officer Attestation Placeholder

**Signature:** ________________________

**Role:** Chief Risk Officer / COO

**Date:** {{date}}

---

## 📄 PAGE 7 — OPTIONAL FORENSIC ANNEX (BOARD SAFE)

| Domain | Timestamp Bucket | Pattern |
|--------|------------------|---------|
| Fraud | {{forensic_fraud_ts}} | {{forensic_fraud_pattern}} |
| AML | {{forensic_aml_ts}} | {{forensic_aml_pattern}} |

---

**Report Version:** 1.0  
**Template Version:** 1.0  
**Generated By:** Risk Brain Reporter v1

---

**Mandatory Footer (Repeated):**

> "This document reports shadow-only AI intelligence. No AI-origin financial execution is possible by design."
